version: "3.1"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - hmpps
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
    tmpfs:
      - /var/lib/postgresql

  redis:
    image: "redis:6.2.3-alpine"
    networks:
      - hmpps
    container_name: redis
    ports:
      - "6379:6379"

  oauth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: oauth
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/auth/health"]
    environment:
      - SERVER_PORT=9090
      - SPRING_PROFILES_ACTIVE=dev

  offender-assessment-api:
    image: quay.io/hmpps/offender-assessments-api:latest
    restart: always
    networks:
      - hmpps
    container_name: offender-assessment-api
    depends_on:
      - oauth
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - OAUTH_ENDPOINT_URL=http://oauth:9090/auth

  hmpps-assessment-api:
    image: quay.io/hmpps/hmpps-assessments-api:latest
    restart: always
    networks:
      - hmpps
    container_name: hmpps-assessment-api
    depends_on:
      - oauth
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - OAUTH_ENDPOINT_URL=http://oauth:9090/auth

networks:
  hmpps:
