version: '3.1'
services:
  risk-assessment-wiremock:
    image: rodolpheche/wiremock
    container_name: risk-assessment-wiremock
    restart: always
    ports:
      - "9191:8080"
    command: [--verbose]

  risk-assessment-redis:
    image: "redis:6.2.3-alpine"
    networks:
      - risk-assessment-hmpps
    container_name: risk-assessment-redis
    ports:
      - "6379:6379"
networks:
  risk-assessment-hmpps:
