version: '3.1'
services:
  risk-assessment-wiremock:
    image: rodolpheche/wiremock
    container_name: risk-assessment-wiremock
    restart: always
    ports:
      - "9191:8080"
    command: [--verbose]

  redis:
    image: "redis:6.2.3-alpine"
    networks:
      - hmpps
    container_name: redis
    ports:
      - "6379:8080"
networks:
  hmpps:
