apiVersion: v2
appVersion: '1.0'
description: A Helm chart for Kubernetes
name: hmpps-risk-assessment-ui
version: 0.1.0

dependencies:
  - name: gotenberg
    version: 0.1.0
  - name: generic-service
    version: "3.10"
    repository: https://ministryofjustice.github.io/hmpps-helm-charts
  - name: generic-prometheus-alerts
    version: 1.11.6
    repository: https://ministryofjustice.github.io/hmpps-helm-charts
    condition: generic-prometheus-alerts.enabled
