---
generic-service:
  nameOverride: hmpps-risk-assessment-ui

  replicaCount: 2

  image:
    repository: quay.io/hmpps/hmpps-risk-assessment-ui
    tag: app_version    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-assessments-cert

  livenessProbe:
    httpGet:
      path: /health

  readinessProbe:
    httpGet:
      path: /health

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /metrics
    metricsPort: 3001

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-assessments-api:
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
    hmpps-risk-assessment-ui:
      AUTH_CLIENT_ID: "API_CLIENT_ID"
      AUTH_CLIENT_SECRET: "API_CLIENT_SECRET"
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    hmpps-assessments-elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_PASSWORD: "auth_token"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"
    capita-vpn-1: 82.203.33.128/28
    capita-vpn-2: 82.203.33.112/28
    ark-internet-1: "194.33.192.0/25"
    ark-internet-2: "194.33.196.0/25"    

generic-prometheus-alerts:
  targetApplication: hmpps-risk-assessment-ui

gotenberg:
  replicaCount: 2
