generic-service:
  nameOverride: hmpps-risk-assessment-ui

  replicaCount: 2

  serviceAccountName: hmpps-assessments-service-account

  image:
    repository: quay.io/hmpps/hmpps-risk-assessment-ui
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    v1_2_enabled: true
    v0_47_enabled: false
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-assessments-cert

  livenessProbe:
    httpGet:
      path: /health

  readinessProbe:
    httpGet:
      path: /health

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /metrics
    metricsPort: 3001

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    S3_REGION: "eu-west-2"
    SNS_REGION: "eu-west-2"
    SHOW_NOTIFICATION: false
    NOTIFICATION_HEADER: " "
    NOTIFICATION_BODY: " "
    DISPLAY_MAINTENANCE_PAGE: false
    MAINTENANCE_PAGE_TEXT: " "

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-assessments-api:
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
    hmpps-risk-assessment-ui:
      AUTH_CLIENT_ID: "API_CLIENT_ID"
      AUTH_CLIENT_SECRET: "API_CLIENT_SECRET"
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    hmpps-assessments-elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_PASSWORD: "auth_token"
    hmpps-assessments-s3:
      S3_BUCKET_NAME: "bucket_name"
    hmpps-domain-events-topic:
      SNS_TOPIC_ARN: "topic_arn"

  allowlist:
    capita-vpn-1: 82.203.33.128/28
    capita-vpn-2: 82.203.33.112/28
    ark-nps-hmcts-ttp2: 194.33.192.0/25
    ark-nps-hmcts-ttp4: 194.33.196.0/25
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-risk-assessment-ui

gotenberg:
  replicaCount: 2
