---
# Per environment values which override defaults in hmpps-risk-assessments-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-assessments.service.justice.gov.uk
    contextColour: green

  env:
    HMPPS_ASSESSMENT_API_URL: http://hmpps-assessments-api.hmpps-assessments-prod.svc.cluster.local
    OFFENDER_ASSESSMENT_API_URL: https://offender-prod.aks-live-1.studio-hosting.service.justice.gov.uk
    OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    PDF_CONVERTER_ENDPOINT: http://hmpps-risk-assessment-ui-gotenberg.hmpps-assessments-prod.svc.cluster.local/forms/chromium/convert/html
    SHOW_DETAILED_ERRORS: false
    SHOW_REQUEST_ID_ON_ERROR_PAGE: false
    DEV_ASSESSMENT_ID: "fb6b7c33-07fc-4c4c-a009-8d60f66952c4"
    INGRESS_URL: https://hmpps-assessments.service.justice.gov.uk

  allowlist:
    prisma-access: 128.77.75.64/26
    prp-dia-2: 194.33.216.0/23
    groups:
      - internal
      - probation

generic-prometheus-alerts:
  enabled: true
  targetApplication: hmpps-risk-assessment-ui
  alertSeverity: hmpps-assess-risks-and-needs

