# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
minReadySeconds: 10
maxSurge: 100%
maxUnavailable: 50%

image:
  repository: quay.io/hmpps/hmpps-risk-assessment-ui
  tag: latest
  pullPolicy: Always
  port: 3000

ingress:
  enabled: true
  enable_allow_list: true
  host: dev.hmpps-assessments.service.justice.gov.uk
  cert_secret: hmpps-assessments-cert
  path: /
  identifier: green
  weighting: 100

redis:
  secret: hmpps-assessments-elasticache-redis
  tlsEnabled: true

apiClientSecretName: hmpps-assessments-api
authClientSecretName: hmpps-risk-assessment-ui

env:
  HMPPS_ASSESSMENT_API_URL: http://hmpps-assessments-api.hmpps-assessments-dev.svc.cluster.local
  OFFENDER_ASSESSMENT_API_URL: https://offender-dev.aks-dev-1.studio-hosting.service.justice.gov.uk
  OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
  PDF_CONVERTER_ENDPOINT: http://hmpps-risk-assessment-ui-gotenberg.hmpps-assessments-dev.svc.cluster.local/forms/chromium/convert/html
  SHOW_DETAILED_ERRORS: true
  DEV_ASSESSMENT_ID: "fb6b7c33-07fc-4c4c-a009-8d60f66952c4"
  LOGGING_LEVEL: 'DEBUG'

allow_list:
  office: "217.33.148.210/32"
  health-kick: "35.177.252.195/32"
  mojvpn: "81.134.202.29/32"
  ark-internet-1: "194.33.192.0/25"
  ark-internet-2: "194.33.196.0/25"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"
  global-protect: "35.176.93.186/32"
  capita-vpn-1: 82.203.33.128/28
  capita-vpn-2: 82.203.33.112/28

gotenberg:
  replicaCount: 1

generic-prometheus-alerts:
  enabled: false
