# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
minReadySeconds: 10
maxSurge: 100%
maxUnavailable: 50%

image:
  repository: quay.io/hmpps/hmpps-risk-assessment-ui
  tag: latest
  pullPolicy: Always
  port: 3000

ingress:
  enabled: true
  enable_allow_list: true
  host: dev.hmpps-assessments.service.justice.gov.uk
  cert_secret: hmpps-assessments-cert
  path: /
  identifier: green
  weighting: 0

redis:
  secret: hmpps-assessments-elasticache-redis
  tlsEnabled: true

apiClientSecretName: hmpps-assessments-api
authClientSecretName: hmpps-risk-assessment-ui

env:
  HMPPS_ASSESSMENT_API_URL: http://hmpps-assessments-api.hmpps-assessments-dev.svc.cluster.local
  OFFENDER_ASSESSMENT_API_URL: https://offender-dev.aks-dev-1.studio-hosting.service.justice.gov.uk
  OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
  PDF_CONVERTER_ENDPOINT: http://hmpps-risk-assessment-ui-gotenberg.hmpps-assessments-dev.svc.cluster.local/forms/chromium/convert/html
  SHOW_DETAILED_ERRORS: true
  DEV_ASSESSMENT_ID: "fb6b7c33-07fc-4c4c-a009-8d60f66952c4"

allow_list:
  office: "217.33.148.210/32"
  health-kick: "35.177.252.195/32"
  mojvpn: "81.134.202.29/32"
  quantum: "62.25.109.197/32"
  quantum_alt: "212.137.36.230/32"
  digitalprisons1: "52.56.112.98/32"
  digitalprisons2: "52.56.118.154/32"
  j5-phones-1: "35.177.125.252/32"
  j5-phones-2: "35.177.137.160/32"
  dxc-mitcheldean: "195.92.38.16/28"
  ark-dom1-ttp1: "195.59.75.0/24"
  ark-dom1-farnborough: "194.33.192.0/24"
  ark-dom1-farnborough-psn: "51.247.3.0/24"
  ark-dom1-corsham: "194.33.196.0/24"
  ark-dom1-corsham-psn: "51.247.4.0/24"
  ark-dom1-non-live-1: "194.33.193.0/25"
  ark-dom1-non-live-2: "194.33.197.0/25"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"

gotenberg:
  replicaCount: 1

generic-prometheus-alerts:
  enabled: false
